apply plugin: 'com.android.application'

android {
    compileSdkVersion 33
    buildToolsVersion '30.0.3'
    defaultConfig {
        applicationId 'my.boxman'
        minSdkVersion 21
//        targetSdkVersion 21
        versionCode 9
        versionName "9.99u~"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
    android.applicationVariants.all {
        variant ->
            variant.outputs.all {
                //这里修改apk文件名:
                outputFileName = "BoxMan${defaultConfig.versionName}_${releaseTime()}.apk"
            }
    }
    productFlavors {
    }
    useLibrary 'org.apache.http.legacy'   //解决导入org.apache问题
    lintOptions {   //解决 Generate signed Bundle or APK  打包时报错问题
        checkReleaseBuilds false
        abortOnError false
    }
    compileOptions {
        targetCompatibility JavaVersion.VERSION_1_8
        sourceCompatibility JavaVersion.VERSION_1_8
    }
}

def releaseTime() {
    return new Date().format("yyyyMMdd", TimeZone.getTimeZone("UTC"))
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation files('libs/json-simple-1.1.jar')
}